# Shell variables
# Generated by 'wal'
wallpaper='/home/michael/Pictures/wallpapers/minimal-7.jpg'

# Special
background='#091927'
foreground='#e1e7ee'
cursor='#e1e7ee'

# Colors
color0='#091927'
color1='#77A7D6'
color2='#7FB2E1'
color3='#8DA2B3'
color4='#8DB5DE'
color5='#A7C3E0'
color6='#ADD0EC'
color7='#e1e7ee'
color8='#9da1a6'
color9='#77A7D6'
color10='#7FB2E1'
color11='#8DA2B3'
color12='#8DB5DE'
color13='#A7C3E0'
color14='#ADD0EC'
color15='#e1e7ee'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
