#!/usr/bin/env bash

## Copyright (C) 2020-2024 Aditya Shakya <adi1090x@gmail.com>
##
## Set Wallpaper in Hyprland

WALLPAPER='/home/michael/Pictures/wallpapers/minimal-7.jpg'

swaybg --output '*' --mode fill --image "$WALLPAPER"
